<a href="https://colab.research.google.com/github/Antudas5252/Antudas5252/blob/main/ExerciseNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ex:01-Import the numpy package under the name np()

In [ ]:
import numpy as np

#Ex:02-Print the numpy version and the configuration()

In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#Ex:03-Create a null vector of size 10()

In [ ]:
vec_01 = np.full(shape=(5,2),fill_value=0)
print(vec_01)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
vec_01.size

10

In [ ]:
vec_01=np.zeros(10)

In [ ]:
vec_01

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#Ex:04-How to find the memory size of any array ()

In [ ]:
print(vec_01.nbytes)


80


In [ ]:
print(vec_01.size * vec_01.itemsize)

80


#Ex:05-How to get the documentation of the numpy add function from the command line?

In [ ]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#Ex:06-Create a null vector of size 10 but the fifth value which is 1 ()

In [ ]:
vec_01

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
vec_01[4]=1
print(vec_01)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#Ex:07-Create a vector with values ranging from 10 to 49

In [ ]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#Ex:08-Reverse a vector ()

In [ ]:
vec_02=np.array([1,2,3,4,5])
print(vec_02)

[1 2 3 4 5]


In [ ]:
rev_vec_02=vec_02[::-1]

In [ ]:
rev_vec_02

array([5, 4, 3, 2, 1])

#Ex:09-Create a 3*3 matrix with values ranging from 0 to 8 ()

In [ ]:
mat_01=np.arange(0,9).reshape(3,3)
mat_01

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#Ex:10-Find indices of non-zero elements from [1,2,0,0,4,0] ()

In [ ]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#Ex:11-Create a 3*3 identity matrix ()

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Ex:12-Create a 3*3*3 array with random values

In [ ]:
random_array=np.random.random((3,3,3))
print(random_array)

[[[0.10029382 0.12852032 0.57158259]
  [0.0482384  0.6358044  0.6343018 ]
  [0.66106183 0.00816361 0.12888273]]

 [[0.24701032 0.35603178 0.51483417]
  [0.17168048 0.01776904 0.23213007]
  [0.28997923 0.70497791 0.19957745]]

 [[0.93201893 0.51205027 0.53104678]
  [0.38954248 0.7575797  0.73371808]
  [0.50458851 0.3792881  0.95794895]]]


#Ex:13-Create a 10*10 array with random values and find the minimum and maximum values

In [ ]:
array=np.random.random((10,10))
print(array)

[[0.30810515 0.39207835 0.87041552 0.79622578 0.87228718 0.04469326
  0.86930495 0.845098   0.66176438 0.00409704]
 [0.90929343 0.27057768 0.38760804 0.494806   0.28848456 0.08777913
  0.34853709 0.71115505 0.81001659 0.45565276]
 [0.63506585 0.2888345  0.62957401 0.37043223 0.95482775 0.10560833
  0.81356269 0.28810778 0.24712825 0.93330002]
 [0.63933785 0.10239459 0.61001681 0.36826093 0.42472639 0.60732277
  0.01483141 0.25772075 0.08670541 0.18013404]
 [0.32510003 0.70921797 0.42683583 0.74011504 0.33047778 0.32209654
  0.07457327 0.20786636 0.99033095 0.41307432]
 [0.95035029 0.49620775 0.46175671 0.57173156 0.63466006 0.56850315
  0.60821394 0.67569338 0.78658699 0.42121768]
 [0.11867116 0.61899111 0.33973825 0.24200932 0.58400768 0.71586128
  0.29599306 0.88533084 0.55326111 0.64958606]
 [0.01060828 0.32357458 0.82043928 0.6159583  0.3447624  0.16863824
  0.62797907 0.49998543 0.79496769 0.37871806]
 [0.77832794 0.01182306 0.13316455 0.12823516 0.8573675  0.71699149
  0.68010634

In [ ]:
print(array.max())

0.9903309546137591


In [ ]:
print(array.min())

0.0040970413545531326


#Ex:14-Create a random vector of size 30 and find the mean value

In [ ]:
ran_vec=np.random.random(30)
print(ran_vec)

[0.96583486 0.62446097 0.91733264 0.27836926 0.9781383  0.48545191
 0.1239327  0.00278113 0.19379392 0.03316663 0.68488762 0.33049882
 0.09144622 0.44631092 0.71782087 0.93033774 0.30886032 0.50361631
 0.5689605  0.89054383 0.82242728 0.93475386 0.4654126  0.57268249
 0.74791698 0.97742794 0.83330115 0.91419569 0.86296485 0.86461514]


In [ ]:
print(ran_vec.mean())

0.6024081140682451


#Ex:15-Create a 2d array with 1 on the border and 0 inside

In [ ]:
array=np.ones((5,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Ex:16-How to add a border (filled with 0 ) around an existing array?

In [ ]:
existing_array = np.ones((3,3))
border_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(border_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr=np.zeros((5,5))
arr[1:-1,1:-1]=1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#Ex:17-What is the result of the following expression? ()
0 * np.nan      
np.nan == np.nan    
np.inf > np.nan     
np.nan - np.nan    
np.nan in set ([np.nan])     
0.3 == 3  * 0.1

In [ ]:
import numpy as np
print(0 * np.nan )
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#Ex:18-Create a 5 * 5 matrix with values 1,2,3,4 just below the diagonal ()

In [ ]:
matrix=np.diag([1,2,3,4],k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#Ex:19-Create a 8*8 matrix and fill it with a checkerboard pattern

In [ ]:
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Ex:20-Consider a (6,7,8) shape array , what is the index (x,y,z) of the 100th element? ()

In [ ]:
shape =np.array([6,7,8])
index = np.unravel_index(100,shape)
print(index)

(np.int64(1), np.int64(5), np.int64(4))


#Ex:21-Create a checkerboard 8*8 matrix using the tile function

In [ ]:

Pattern = np.array([[0,1],[1,0]])
checkerboard = np.tile(Pattern,(4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Ex:22-Normalize a 5*5 random matrix ()

In [ ]:
matrix = np.random.random((5,5))
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized_matrix)

[[0.00487149 0.79258219 0.14151448 0.16113309 0.32716661]
 [0.37976606 0.55778124 0.9808533  0.06891399 0.59137598]
 [0.44417691 0.15343795 0.26563234 0.97961355 0.59348332]
 [0.61637418 0.02279447 0.99035701 1.         0.9889687 ]
 [0.25019206 0.         0.64273457 0.52866061 0.31988426]]


#Ex:23-Create a custom dtype that describes a color as four unsigned bytes (RGBA) ()

In [ ]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#Ex:24-Multipy a 5 by 3 matrix by a 3 by 2 matrix(real matrix product)

In [ ]:
matrix_01=np.random.random((5,3))
matrix_02=np.random.random((3,2))
result = np.dot(matrix_01,matrix_02)
print(result)

[[0.78812886 0.36808967]
 [1.10908583 0.47249477]
 [0.94368628 0.44674599]
 [1.36407633 0.58597706]
 [1.14577237 0.51215936]]


In [ ]:
m1=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7]])
m2=np.array([[1,2],[2,3],[3,4]])
result=np.dot(m1,m2)
print(result)

[[14 20]
 [20 29]
 [26 38]
 [32 47]
 [38 56]]


#Ex:25-Given a 1D array , negate all elements which are between 3 and 8,in place ()

In [ ]:
array = np.arange(10)
array[(array>=3) & (array<=8)] *=-1
print(array)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#Ex:26-What is the output of the following script? ( )
#  Author: Jake VanderPlas

print(sum(range(5),-1))     
from numpy import *    
print(sum(range(5),-1))

In [ ]:
# Author: Jake Vanderplas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#Ex:27-Consider an integer vector z,which of these expressions are legal?
z**z    
2 << z >> 2       
z <- z      
1j*z         
z/1/1        
z<z>z

In [ ]:
z = np.array([1,2,3])
print(z**z) #Legal
print(2 << z >> 2) #Legal
print(z <- z) #Not legal
print(1j +z) #legal
print(z/1//1) #legal
print(z<z>z) #not legal


[ 1  4 27]
[1 2 4]
[False False False]
[1.+1.j 2.+1.j 3.+1.j]
[1. 2. 3.]


#Ex:28-What are the result of the following expressions?()


In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-5-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-5-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-5-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#Ex:29-How to round away from zero a float array?()

In [ ]:
arr = np.array([-3.4,3.4,-3.6,3.6])
rounded_arr = np.copysign(np.ceil(np.abs(arr)),arr)
print(rounded_arr)

[-4.  4. -4.  4.]


#Ex:30- How to find common values between two arrays?()

In [ ]:
A = np.array([1,2,3,4,5])
B = np.array([3,4,5,6,7])
print(np.intersect1d(A,B))

[3 4 5]


#Ex:31-How to ignore all numpy warnings?()

In [ ]:
import warnings
warnings.filterwarnings("ignore")

#Ex:32-Is the following expressions true?()
np.sqrt(-1)  == np.emath.sqrt(-1)

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#Ex:33-How to get the dates of yesterday,today and tomorrow?( )

In [ ]:
import datetime

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print(yesterday,today,tomorrow)

2025-04-03 2025-04-04 2025-04-05


#Ex:34-How to get all the dates corresponding to the month of July 2016?( )

In [ ]:
import datetime
july_2016 = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#Ex:35-How to compute ((A+B)*(-A/2)) in place (without copy)? ()

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
A += B
A = A * (-A/2)
print(A)

[-12.5 -24.5 -40.5]


#Ex:36-Extract the integer part of a random array of positive numbers using 4 different methods ()

In [ ]:
arr = np.random.random(5) * 10
print(arr.astype(int)) # Method-01
print(np.floor(arr)) # Method-02
print(np.ceil(arr) - 1) # Method-03
print(np.trunc(arr)) # Method-04

[5 1 2 9 4]
[5. 1. 2. 9. 4.]
[5. 1. 2. 9. 4.]
[5. 1. 2. 9. 4.]


#Ex:37-Create a 5*5 matrix with row values ranging from 0 to 4

In [ ]:
matrix = np.tile(np.arange(0,5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#Ex:38-Consider a generator function that generates 10 integers and use it to build an array()

In [ ]:
def generator():
  for i in range(10):
    yield i
arr = np.fromiter(generator(),dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#Ex:39-Create a vector of size 10 with values ranging from 0 to 1,both excluded ()

In [ ]:
rand_vec = np.linspace(0,1,12) [1:-1]
print(rand_vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#Ex:40-Create a random vector of size 10 and sort it ()

In [ ]:
random_vec = np.random.rand(10)
random_vec.sort()
print(random_vec)

[0.18812957 0.21097626 0.44867934 0.47387504 0.55793373 0.57552783
 0.75720465 0.78088627 0.80923259 0.968474  ]


#Ex:41-How to sum a small array faster than np.sum?()

In [ ]:
arr = np.array([1,2,3,4])
print(np.add.reduce(arr))

10


#Ex:42-Consider two random array A and B,check if they are equal ()

In [ ]:
arr_1 = np.random.rand(5)
arr_2 = np.random.rand(5)
print(np.array_equal(arr_1,arr_2))

False


#Ex:43-Make an array immutable read only ()

In [ ]:
arr = np.array([1,2,3,4,5])
arr.flags.writeable = False #make array read only


#Ex:44-Consider a random 10*2 matrix representing cartesian coordinates ,convert them to polar coordinates

In [ ]:
cartesian = np.random.random((10,2))
x,y = cartesian[:,0], cartesian[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan(y,x)

polar = np.column_stack((r,theta))
print(polar)

[[0.8035416  0.5965545 ]
 [1.00138203 0.76618757]
 [1.22721323 0.75676489]
 [0.85164413 0.23223368]
 [0.73982745 0.27007341]
 [0.42356817 0.20551356]
 [1.04333272 0.34950238]
 [0.90555234 0.05619251]
 [0.66641117 0.52343026]
 [0.13712904 0.04282719]]


#Ex:45-Create random vector of size 10 and replace the maximum value by 0 ()

In [ ]:
vec_03 = np.random.rand(10)
vec_03[vec_03.argmax()] = 0
print(vec_03)

[0.81807251 0.44336713 0.         0.15680989 0.46500688 0.11779604
 0.18095839 0.32080786 0.55141039 0.74961775]


#Ex:46-Create a structured array with x and y coordinates covering the [0,1]*[0,1] area ()

In [ ]:
dtype = [('x',float),('y',float)]
grid = np.zeros((10,10),dtype=dtype)

grid['x'],grid['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(grid)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#Ex:47-Given two arrays, X and Y ,construct the Cauchy matrix C(Cij=1/(Xi-Yi)) ()

In [ ]:
X = np.arange(1,6)
Y = np.arange(1,6)[:,None]
C = 1.0/(X-Y+np.eye(len(X)))
print(C)

[[ 1.          1.          0.5         0.33333333  0.25      ]
 [-1.          1.          1.          0.5         0.33333333]
 [-0.5        -1.          1.          1.          0.5       ]
 [-0.33333333 -0.5        -1.          1.          1.        ]
 [-0.25       -0.33333333 -0.5        -1.          1.        ]]


#Ex:48-Print the minimum and maximum representable value for each numpy scaler type ()

In [ ]:
types = [np.int8,np.int16,np.int32,np.int64,np.float32,np.float64]

for dtype in types:
  if np.issubdtype(dtype,np.integer):
    info = np.iinfo(dtype)
  else:
      info = np.finfo(dtype)
      print(f"{dtype}: Min={info.min}, Max={info.max}")

<class 'numpy.float32'>: Min=-3.4028234663852886e+38, Max=3.4028234663852886e+38
<class 'numpy.float64'>: Min=-1.7976931348623157e+308, Max=1.7976931348623157e+308


#Ex:49-How to print all the values of an array?()

In [ ]:
arr = np.random.rand(10)
print(arr)

[0.42529837 0.76659805 0.79560676 0.81182074 0.05099455 0.43261799
 0.83089833 0.28086915 0.50132471 0.87127212]


#Ex:50-How to find the closest value in a vector?()

In [ ]:
vec = np.random.rand(10)
scaler = 0.5
closest_value = vec[np.abs(vec - scaler).argmin()]
print(closest_value)


0.49269965424445283


#Ex:51-Create a structured array representing a position (x,y) and a color (r,g,b)


In [ ]:
np.zeros(10, dtype=[('position',[('x',float),('y',float)]),('color',[('r',float),('g',float),('b',float)])])

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#Ex:52-Consider a random vector with shape (100,2) representing coordinates ,find point by point distances

In [ ]:
a = np.random.random((100,2))
distance = np.sqrt(((a-a[:,np.newaxis])**2).sum(axis=2))
print(distance)

[[0.         0.39505274 0.01607621 ... 0.08829734 0.3276482  0.12580642]
 [0.39505274 0.         0.40482392 ... 0.30793986 0.47145729 0.27159436]
 [0.01607621 0.40482392 0.         ... 0.10027538 0.34200528 0.1377666 ]
 ...
 [0.08829734 0.30793986 0.10027538 ... 0.         0.31275754 0.03754427]
 [0.3276482  0.47145729 0.34200528 ... 0.31275754 0.         0.31189002]
 [0.12580642 0.27159436 0.1377666  ... 0.03754427 0.31189002 0.        ]]


#Ex:53-How to convert a float (32 bits) array into an integer (32 bits) in place?()

In [ ]:
A= np.array([1.5,2.3,3.7],
dtype=np.float32)
A = A.astype(np.int32)
print(A)

[1 2 3]


#Ex:54-How to read the following file?()
1,2,3,4,5    
6, , ,7,8      
 , ,9,10,11

In [ ]:
data = np.genfromtxt('file.txt',delimiter=',',dtype=np.int32)
print(data)

#Ex:55-What is the equivalent of enumerate for numpy arrays?()

In [ ]:
for index,value in np.ndenumerate(np.array([1,2,3])):
  print(index,value)

(0,) 1
(1,) 2
(2,) 3


#Ex:56-Generate a generic 2D Gaussian-like array?()

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,100),np.linspace(-1,1,100))
d = np.sqrt(x*x+y*y)
sigma,mu = 1.0,0.0
gaussian = np.exp(-((d-mu)**2)/(2*sigma**2))
print(gaussian)

[[0.36787944 0.37531033 0.38273509 ... 0.38273509 0.37531033 0.36787944]
 [0.37531033 0.38289132 0.39046605 ... 0.39046605 0.38289132 0.37531033]
 [0.38273509 0.39046605 0.39819064 ... 0.39819064 0.39046605 0.38273509]
 ...
 [0.38273509 0.39046605 0.39819064 ... 0.39819064 0.39046605 0.38273509]
 [0.37531033 0.38289132 0.39046605 ... 0.39046605 0.38289132 0.37531033]
 [0.36787944 0.37531033 0.38273509 ... 0.38273509 0.37531033 0.36787944]]


#Ex:57-How to randomly place p elements in a 2D array?()

In [ ]:
n = 10
p = 5
Z = np.zeros((n,n))
indices = np.random.choice(n*n,p,replace=False)
Z[np.unravel_index(indices,(n,n))] = 1
print(Z)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#Ex:58-Subtract the mean of each row of a matrix()

In [ ]:
X = np.random.random((5,10))
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.54205336 -0.46943607 -0.13574469  0.30114042  0.27997835  0.43806267
   0.14105171 -0.00267804  0.29484353 -0.30516451]
 [-0.20609973  0.16455499  0.14858946  0.37264542  0.42818972 -0.38252829
  -0.18486816 -0.15321193 -0.10875073 -0.07852075]
 [ 0.13194334 -0.08816827 -0.64708309  0.15560354  0.15898655 -0.04347239
   0.10960351  0.23499592  0.04297091 -0.05538003]
 [ 0.15031873  0.38571501 -0.59377879  0.2702508   0.29075564 -0.01510616
  -0.16008515 -0.21873167 -0.06497966 -0.04435875]
 [ 0.15100424 -0.09801885 -0.2496936   0.14745776 -0.31956224  0.46347839
  -0.03978454 -0.08016429  0.08379713 -0.058514  ]]


#Ex:59-How to sort an array by the nth column?

In [ ]:
A = np.random.random((10,3))
A = A[A[:,1].argsort()]
print(A)

[[0.12241283 0.07466796 0.22680449]
 [0.23536836 0.10425348 0.11206851]
 [0.55651108 0.19066206 0.10978693]
 [0.36223798 0.27503442 0.749249  ]
 [0.61374832 0.28112989 0.10477962]
 [0.71695315 0.32995246 0.44487013]
 [0.78706503 0.572081   0.53674053]
 [0.63795337 0.82585089 0.54980385]
 [0.05601597 0.88006408 0.14427892]
 [0.8866664  0.94850706 0.63533421]]


#Ex:60-How to tell if a given 2D array has null columns?()

In [ ]:
x = np.random.random((10,10))
print(~x.any(axis=0))

[False False False False False False False False False False]


#Ex:61-Find the nearest value from a given value in an array

In [ ]:
import numpy as np
arr = np.random.uniform(0,100,10)
value = 50
nearest_value = arr[np.abs(arr-value).argmin()]
print(nearest_value)

52.93634986531587


#Ex:62-Sum of arrays (1,3) and (3,1) using an iterator

In [ ]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
iterator = np.nditer([A,B,None])
for x,y,z in iterator:
  z[...] = x + y
print(iterator.operands[2])
#

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#Ex:63-Create an array class with name attribute

In [ ]:
class NamedArray(np.ndarray):
  def __new__(cls,array,name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
    def __array_finalize__(self,obj):
      if obj is None:
        return
      self.name = getattr(obj,'name','no name')
arr = NamedArray(np.arange(10),'range_10')

#Ex:64-Add 1 to each element indexed by another vector (handle repeats)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z,I,1)
print(Z)

[3. 3. 4. 2. 2. 1. 2. 4. 4. 5.]


#Ex:65-Accumulate elements of vector X into F based on index list I

In [ ]:
X = [1,2,3,4,5]
I = [0,1,2,3,4]
F = np.zeros(5)
np.add.at(F,I,X)
print(F)

[1. 2. 3. 4. 5.]


#Ex:66-Count unique colors in (w,h,3) image

In [ ]:
image = np.random.randint(0,2,(10,10,3)).astype(np.ubyte)
unique_colors = len(np.unique(image.reshape(-1,image.shape[-1]),axis=0))
print(unique_colors)

8


#Ex:67-Sum over the last two axis of a 4D array()

In [ ]:
A = np.random.rand(3,4,5,6)
sum_result = A.sum(axis=(-2,-1))
print(sum_result)

[[15.70648245 13.48687603 15.72016386 17.05723624]
 [16.97072541 15.39601141 14.26100793 15.23985511]
 [16.32452614 15.70878486 12.7040892  16.33049347]]


#Ex:68-Compute mean of subsets using subset indices

In [ ]:
D = np.random.rand(100)
S = np.random.randint(0,10,100)
mean_result = np.array([np.mean(D[S==i]) for i in range(10)])
print(mean_result)

[0.58587239 0.65611637 0.42384629 0.54965755 0.35401812 0.49986264
 0.49338558 0.62970202 0.51352469 0.55658599]


#Ex:69-Diagonal of a dot product

In [ ]:
A = np.random.random((3,3))
B = np.random.random((3,3))
dot_product = np.dot(A,B)
diagonal = np.diag(dot_product)
print(diagonal)

[1.05151703 0.49282809 1.62348802]


#Ex:70-New vector with 3 zeros between each value

In [ ]:
z = np.array([1,2,3,4,5])
new_vector = np.zeros(len(z) + (len(z)-1)*3)
new_vector[::4] = z
print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#Ex:71-Multiply (5,5,3) with (5,5)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
result = A * B[:,:,None]
print(result)


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#Ex:72-Swap two rows of an array

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A[[0,1]] = A[[1,0]]
print(A)

[[4 5 6]
 [1 2 3]]


#Ex:73-Unique line segments from triangles

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.sort(faces[:,[[0,1],[0,2],[1,2]]].reshape(-1,2),axis=1)
np.unique(F,axis = 0)

array([[ 0,  9],
       [ 0, 33],
       [ 3,  6],
       [ 3, 13],
       [ 5, 19],
       [ 5, 89],
       [ 6, 13],
       [ 8, 25],
       [ 8, 44],
       [ 9, 33],
       [19, 89],
       [22, 25],
       [22, 33],
       [25, 33],
       [25, 44],
       [27, 59],
       [27, 90],
       [36, 52],
       [36, 79],
       [44, 56],
       [44, 78],
       [52, 79],
       [56, 64],
       [56, 71],
       [56, 78],
       [59, 90],
       [62, 86],
       [62, 99],
       [64, 71],
       [86, 99]])

#Ex:74-Recover array A from np.bincount

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


#Ex:75-Sliding window average

In [ ]:
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return  ret[n-1:]/n
    Z = np.arange(20)
    print(moving_average(Z,n=3))

#Ex:76-Rolling window from 1D array

In [ ]:
Z = np.arange(10)
print(np.lib.stride_tricks.sliding_window_view(Z,3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#Ex:77-Inplace boolean negation or sign change

In [ ]:
Z = np.array([True,False,True])
np.logical_not(Z,out=Z)
Z = np.array([1,-1,0])
np.negative(Z,out=Z)
print(Z)

[-1  1  0]


#Ex:78-Distance from point to each line (P0[i],P1[i])

In [ ]:
def distance_point_line(p,P0,P1):
    return np.linalg.norm(np.cross(P1-P0,P0-p),axis=1)/np.linalg.norm(P1-P0,axis=1)

#Ex:79-Distance from each point in P to each line (P0[i],P1[i])

In [ ]:
def distance_all_points(p,P0,P1):
    return np.array([[np.linalg.norm(np.cross(p1-p0,p0-p))/np.linalg.norm(p1-p0)
                             for p0,p1 in
      zip(P0,P1)] for p in p])

#Ex:80-Consider an arbitrary array ,write a function that extract a  subpart with a fixed shape and centered on a given element ()

In [ ]:

import numpy as np
def extract_subarray(arr,center,shape,fill_value=111):
   arr = np.asarray(arr)
   out = np.full(shape,fill_value)
   start = [c-s//2 for c,s in zip(center,shape)]
   end = [s + st for s,st in zip(shape,start)]

   src_slices = [slice(max(0,st),min(e,a.shape[i])) for i,(st,e) in enumerate(zip(start,end))]
   dst_slices = [slice(max(0,-st),min(a.shape[i] - st,sh)) for i,(st,sh) in enumerate(zip(start,shape))]
   out[tuple(dst_slices)] = arr[tuple(src_slices)]
   return out

#Ex:81-Generate a rolling window array

In [ ]:
z = np.arange(1,15+1)
R = np.lib.stride_tricks.sliding_window_view(z,window_shape=4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]]


#Ex:82-Compute a matrix rank

In [ ]:
Z = np.random.rand(10,10)
rank = np.linalg.matrix_rank(Z)
print(rank)


10


#Ex:83-Find the most frequent value in an array()

In [ ]:
z = np.random.randint(0,10,50)
most_freq = np.bincount(z).argmax()
print(most_freq)


9


#Ex:84-Extract all contiguous 3*3 blocks from a random 10*10 matrix

In [ ]:
X = np.random.random((10,10))
blocks = np.lib.stride_tricks.sliding_window_view(X,(3,3))
print(blocks.shape)

(8, 8, 3, 3)


#Ex:85-Create a 2D array subclass such that Z[i,j]==Z[j,i]

In [ ]:
class symmetricArray(np.ndarray):
    def  __getitem__(self,idx):
           i,j = idx
           return
           super().__getitem__((max(i,j),min(i,j)))

           z = np.array([[1,2],[3,4]]).view(symmetricArray)
           print(z[1,0])


#Ex:86-Compute the sum of p matrix-vector products(shapes:p matrices of (n,n),p vectors of (n,1),result shape (n,1))

In [ ]:
p = 5
n= 3
matrices = np.random.rand(p,n,n)
vectors = np.random.rand(p,n,1)

result = np.sum(np.matmul(matrices,vectors),axis=0)
print(result.shape)

(3, 1)


#Ex:87-Block sum on a 16*16 array (block size = 4*4)

In [ ]:
Y = np.random.random((16,16))
block_sum = Y.reshape(4,4,4,4).sum(axis=(2,3))
print(block_sum.shape)

(4, 4)


#Ex:88-Implement Conway's Game of Life using Numpy

In [ ]:
def game_of_life_step(Z):
  neighbors = sum(np.roll(np.roll(Z,i,0),j,1) for i in (-1,0,1)
         for j in (-1,0,1) if(i!=0 or j!=0))
  return (neighbors == 3) | ((Z == 1) & (neighbors == 2))

  Z = np.random.randint(0,2,(5,5))
  Z = game_of_life_step(Z)


#Ex:89-Get the n largest values of an array()

In [ ]:
Z = np.random.rand(10)
n=3
largest = Z[np.argsort(Z)[-n:]]
print(largest)

[0.74141798 0.89285552 0.91276894]


#Ex:90-Cartesian product from multiple vectors

In [ ]:
from itertools import product

vectors = [np.array([1,2]),np.array([3,4])]
cartesian = np.array(list(product(*vectors)))
print(cartesian)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


#Ex:91-Create a record array from a regular array()

In [ ]:
Z = np.array([[1,2],[3,4]],dtype=[('x','i4'),('y','i4')])
print(Z)

[[(1, 1) (2, 2)]
 [(3, 3) (4, 4)]]


#Ex:92-Compute Z to the power of 3 using 3 different methods()

In [ ]:
Z = np.array([1,2,3,4])
print(Z ** 3) #method-1
print(np.power(Z,3)) #method-2
print(np.array([x**3 for x in Z])) #method-3

[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]


#Ex:93-Find rows of A that contain all elements of each row of B(order doesn't matter)

In [ ]:
A = np.array([[1,2,3],[5,6,7],[3,1,2],[7,5,6],[8,9,10]])
B = np.array([[1,2],[5,6]])

result = []
for b_row in B:
    mask = [np.all(np.isin(b_row,a_row)) for a_row in A]
    result.append(A[mask])
print(result)

[array([[1, 2, 3],
       [3, 1, 2]]), array([[5, 6, 7],
       [7, 5, 6]])]


#Ex:94-Extract rows with unequal values(e.g.,no duplicates in row)

In [ ]:
z = np.array([[1,2,3],[2,2,3],[4,5,6]])
unique_rows = z[np.array([len(set(row)) == len(row)
         for row in z])]
print(unique_rows)

[[1 2 3]
 [4 5 6]]


#Ex:95-Convert a vector of ints into matrix binary representation

In [ ]:
Z = np.array([1,2,3,4])
binary_matrix = ((Z[:,None] & (1 << np.arange(8))) > 0).astype(int)
print(binary_matrix)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


#Ex:96-Extract unique rows from a 2D array()

In [ ]:
z= np.array([[1,2],[3,4],[1,2],[5,6]])
unique_rows = np.unique(z,axis=0)
print(unique_rows)


[[1 2]
 [3 4]
 [5 6]]


#Ex:97-einsum for inner,outer,sum,and multiply

In [ ]:
A = np.array([1,2])
B = np.array([3,4])

print(np.einsum('i,i->',A,B))   #inner product
print(np.einsum('i,j->ij',A,B)) #outer product
print(np.einsum('i->',A))        #sum
print(np.einsum('i,i->i',A,B))   #multiplication

11
[[3 4]
 [6 8]]
3
[3 8]


#Ex:98-Sample a path (X,Y) using equidistant points()

In [ ]:
X = np.linspace(0,10,10)
Y = np.sin(X)


dist = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumdist = np.concatenate([[0],np.cumsum(dist)])
target = np.linspace(0,cumdist[-1],50)
from scipy.interpolate import interp1d
fx = interp1d(cumdist,X)
fy = interp1d(cumdist,Y)
x_interp = fx(target)
y_interp = fy(target)
print(x_interp)
print(y_interp)

[ 0.          0.1917851   0.3835702   0.5753553   0.76714039  0.95892549
  1.16177742  1.4071605   1.65254359  1.89792667  2.14330976  2.34726085
  2.53157182  2.7158828   2.90019378  3.08450476  3.26881573  3.46475232
  3.66695015  3.86914797  4.0713458   4.27354363  4.48127043  4.7191888
  4.95710716  5.19502552  5.43294388  5.64276735  5.82271605  6.00266474
  6.18261344  6.36256213  6.54251083  6.73330254  6.94822321  7.16314389
  7.37806456  7.59298524  7.80941803  8.03512546  8.2608329   8.48654033
  8.71224777  8.92773853  9.10644877  9.28515902  9.46386926  9.64257951
  9.82128975 10.        ]
[ 0.          0.15468868  0.30937736  0.46406604  0.61875471  0.77344339
  0.8915879   0.86928873  0.84698956  0.82469039  0.80239122  0.68428464
  0.52076224  0.35723984  0.19371744  0.03019504 -0.13332735 -0.28208476
 -0.42289012 -0.56369548 -0.70450084 -0.84530619 -0.9544001  -0.8903301
 -0.8262601  -0.76219011 -0.69812011 -0.58352993 -0.41521897 -0.24690801
 -0.07859705  0.08971391  0

#Ex:99-Given an integer n and a 2D array X,select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees i.e,the rows which only contain integers and which sum to n()

In [ ]:
X = np.array([[1,1,2],[0.5,1.5,2],[2,2,0],[1,1,1]])

mask = (np.all(X == X.astype(int),axis=1)) & (np.sum(X,axis=1) == n)
result = X[mask]
print(result)

[[1. 1. 1.]]


#Ex:100-Complete bootstrapped 95% confidence interval for the mean of a 1D array()

In [ ]:
X = np.random.rand(1000)
N = 1000

means = [np.mean(np.random.choice(X,size=len(X),replace=True)) for _ in range(N)]
conf_int = np.percentile(means,[2.5,97.5])
print("95% confidence interval:",conf_int)

95% confidence interval: [0.46047542 0.49659871]
